---

- name: NODE_EXPORTER | Add environment file
  template:
    src: node_exporter.environment.j2
    dest: "{{ node_exporter_environment_path }}/node_exporter"
    mode: 0644
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  notify: restart node_exporter

- name: NODE_EXPORTER | Add texfile collector files
  vars:
    filename: "{{ item.key }}"
    metrics: "{{ item.value }}"
  template:
    src: textfile_collector_file.j2
    dest: "{{ node_exporter_textfile_collector_dir }}/{{ filename }}.prom"
    mode: 0644
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  notify: restart node_exporter
  when: node_exporter_textfile_collector_files is defined
  with_dict: "{{ node_exporter_textfile_collector_files }}"

- name: NODE_EXPORTER | Copy logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/node_exporter
    mode: 0644
    owner: root
    group: root
  when: node_exporter_log_path is defined and node_exporter_logrotate_enabled
