# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Madrid"
  end

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 128
    virtualbox.cpus = 1
  end

  config.vm.define "node_exporter" do |node_exporter|
    node_exporter.vm.box = "debian/jessie64"
    node_exporter.vm.network "private_network", ip:"10.0.0.2"
    node_exporter.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
      ansible.sudo = true
    end
  end

end
